### ISSUE TITLE
Problème avec les valeurs par défaut de type enum contenant des underscore

### ISSUE THREAD

**Issue by benoitguigal** [Zhouzi/graphql-codegen-factories#2]
J'ai défini un type enum de la façon suivante:

```graphql
enum Status {
  TO_BE_VERIFIED
  VERIFIED
}
```
puis un type contenant ce champ status

```graphql
type Company {
  status: Status
}
```

Le mock généré est 

```typescript
export function createCompanyMock(props: Partial<Company>): Company {
  return {
    status: Status.To_Be_Verified // error, should be Status.ToBeVerified
  }
}
```

**Comment by Zhouzi** [comment]
Merci pour le signalement 🙏 Ce bug a été corrigé dans https://github.com/Zhouzi/graphql-codegen-factories/commit/b7814e8f67ed8353c71456218f1671b84ae35d62 et publié dans la version 0.0.8. Fais moi signe si tu rencontres toujours des soucis après avoir fait la mise à jour 😉
