### ISSUE TITLE
Setup a realistic demo example

### ISSUE THREAD

**Issue by zhouzi** [zhouzi/graphql-codegen-factories#33]
Currently the example is pretty basic and is not a very good representation of what the plugin does and how it can be useful. It would be great to replace it with an actual React application and GraphQL server. This way it could showcase how this plugin can be used and what it is used for. Also, this application would serve as integration tests (we can build it and verify the types).

It should use as many GraphQL features as possible, for example unions, interfaces, fragments, directives, and aliases. It should also show different ways of taking advantage of this plugin, for example by seeding a database (probably in-memory, a real database would be overkill and a pain to setup in StackBlitz) and by mocking data in tests (backend and frontend).

**Comment by ertrzyiks** [comment]
Do you think of a better example in the repo or setting up a website with more examples online?

**Comment by ertrzyiks** [comment]
@zhouzi feel free to list the yummy project on the list 👍 The gatsby sub-project [blog](https://github.com/yummy-recipes/yummy/tree/master/apps/blog) already adopted the beta.2 version and I will be updating it with new newer versions.

**Comment by zhouzi** [comment]
I have been thinking about a small app that would showcase the use cases for this plugin but it would be too much work for little result. I finally chose to stick with the previous approach of having [multiple examples](https://gabinaureche.com/graphql-codegen-factories/#examples). I will probably add more of them.

@ertrzyiks your project is now also listed on this page 👍
